aws:
  access_key: YOUR_AWS_ACCESS_KEY
  secret: YOUR_AWS_SECRET_KEY
  region: "YOUR_REGION" # 默认区域
  s3:
    bucket: "YOUR_S3_BUCKET"
    region: "YOUR_REGION"
    url_prefix: https://YOUR_BUCKET.s3.YOUR_REGION.amazonaws.com
  sqs:
    default:
      region: YOUR_REGION
      queue_url: https://sqs.YOUR_REGION.amazonaws.com/YOUR_ACCOUNT_ID/YOUR_QUEUE_NAME-
      queue_name: YOUR_QUEUE_NAME
  cloudwatch:
    region: "YOUR_REGION"
    log_group: "YOUR_LOG_GROUP"
    log_stream_prefix: "app-logs-"
    retention_days: 30
    async: true
    buffer_size: 100
    flush_interval: 5
