redis:
  addr: "YOUR_REDIS_ADDR"
  password: "YOUR_REDIS_PASSWORD"
  db: 0

# Example configuration:
# redis:
#   addr: "localhost:6379"
#   password: ""
#   db: 0

# Environment variables (overrides config file):
# REDIS_ADDR=localhost:6379
# REDIS_PASSWORD=your_password